- name: mysql setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql-setup

- name: setup root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1 

  