- name: add user
  ansible.builtin.user:
    name: roboshop

- name: remove app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: crete app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: "download the {{component}} application"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp

- name: "extract {{component}} app"
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes
